### ISSUE TITLE
Setup CI for Qt crates

### ISSUE THREAD

**Issue by Riateche** [rust-qt/cpp_to_rust#11]
Now that cpp_to_rust runs on Linux, Mac OS and Windows with Travis and Appveyor, we need to setup the same process for Qt crates. They already have a build configuration for Linux, but it needs to be expanded.

**Comment by Trolldemorted** [comment]
Did you add CI scripts for the qt_* crates (If yes, where are they?)? They would be really helpful to find out how we can build the crates on windows.
