### ISSUE TITLE
Runtime error with a simple application.

### ISSUE THREAD

**Issue by o01eg** [rust-qt/cpp_to_rust#62]
rust 1.21.0 x64 msvc
MS VS 2017
Qt 5.9.2
clang 5.0.0

main.rs:
```rust
extern crate qt_core;
extern crate qt_gui;
extern crate qt_widgets;
extern crate qt_ui_tools;

use qt_widgets::application::Application;

fn main() {
	Application::create_and_exit(|app| {
		println!("Hello, Qt!");
		let r = Application::exec();
		println!("Bye, Qt!");
		r
	});
}
```

I get runtime error:
![qt](https://user-images.githubusercontent.com/397177/31859889-ae9162f2-b71a-11e7-9fd1-6940502770fd.png)

> Entry point for procedure `?inputMethodQuery@QComboBox@@QEBA?AVQVariant@@W4InputMethodQuery@Qt@@AEBV2@@Z` not found in Qt5Widgest.dll library.

Unmangled name is 
```c++
public: class QVariant __cdecl QComboBox::inputMethodQuery(enum Qt::Input
MethodQuery,class QVariant const & __ptr64)const __ptr64
```

**Comment by Riateche** [comment]
I think this error means that the Qt libraries available at runtime are not the same as libraries used for building the crates (otherwise the error would happen when building). Is the folder containing Qt DLLs aded to PATH?

**Comment by o01eg** [comment]
I suppose it loads Qt5Widgets from cmake which also added to PATH. I'll trying to reinstall cmake without GUI.

**Comment by o01eg** [comment]
Yep, it works without cmake in PATH but looks like cmake installs only with GUI and Qt libraries in `bin`.

**Comment by o01eg** [comment]
No, i was something other but it fixed by copiyng Qt libraries to project folder.
